set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle

" Use Vundle to manage plugins
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'vim-scripts/CSApprox'
Bundle 'Pychimp/vim-luna'
Bundle 'bling/vim-airline'
Bundle 'kien/ctrlp.vim'
Bundle 'Valloric/YouCompleteMe'
Bundle 'scrooloose/syntastic'
Bundle 'edkolev/tmuxline.vim'

set nowrap

" Use 3 spaces by default for indentation
set expandtab
set tabstop=3
set shiftwidth=3

set backspace=2

set autoindent smartindent
set smarttab

" Use 2 spaces for ruby code and html
au FileType ruby,eruby setl tabstop=2 shiftwidth=2
au FileType html setl tabstop=2 shiftwidth=2

" Paragraph formatting options
au FileType plaintex,tex setl textwidth=80 formatoptions=atw

set vb t_vb=

set laststatus=2
set encoding=utf-8
set noshowmode

set background=dark
colorscheme luna

set cursorline

" airline settings
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'bubblegum'
"let g:airline_left_sep = ''
"let g:airline_right_sep = ''
let g:airline_powerline_fonts = 1

" GUI settings
if has("gui_running")
   set guioptions-=m
   set guioptions-=T
   set guioptions-=r

   " Get rid of blinking cursor
   set gcr=a:blinkon0
endif

" Global local configuration
if filereadable(expand("~/.vimrc.local"))
   so ~/.vimrc.local
endif

" Remove delay in exiting insert mode when pressing <ESC>
set noesckeys

" Set system clipboard as default
if has("unix") && substitute(system("uname"), "\n", "", "") == "Linux"
   " Set X clipboard as default
   set clipboard=unnamedplus
else
   set clipboard=unnamed
endif

let g:ycm_global_ycm_extra_conf = expand("~/.vim/ycm_extra_conf.py")

syntax on
filetype on
filetype plugin on
filetype indent on
