filetype off
set rtp+=~/.vim/bundle/vundle

" Use Vundle to manage plugins
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'Lokaltog/vim-powerline'
Bundle 'Rip-Rip/clang_complete'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'tpope/vim-surround'
Bundle 'benmills/vimux'

syntax on

set nocompatible
set backspace=2

set number
set ruler
set nowrap

" Use 3 spaces by default for indentation
set expandtab
set tabstop=3
set shiftwidth=3

set autoindent
set smartindent

filetype on
filetype plugin on
filetype indent on

" Use 2 spaces for ruby code
autocmd FileType ruby set tabstop=2 shiftwidth=2
autocmd FileType eruby set tabstop=2 shiftwidth=2

set vb t_vb=

set background=dark
colorscheme smyck

set laststatus=2
set encoding=utf-8

" GUI settings
if has("gui_running")
   set guioptions-=m
   set guioptions-=T
   set guioptions-=r
   set cursorline

   " Get rid of blinking cursor
   set gcr=a:blinkon0
endif

" Global local configuration
if filereadable(expand("~/.vimrc.local")) 
   so ~/.vimrc.local
endif

" Load custom vimrc if it exists in the directory
" vim was opened in
if filereadable("vimrc.custom") 
   so vimrc.custom
endif

" Keybindings
map <F9> :PromptVimTmuxCommand<Enter>
map <F10> :RunLastVimTmuxCommand<Enter>

" Plugin settings
let g:EasyMotion_leader_key = ','
