setopt CORRECT
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS
setopt AUTO_PUSHD

HISTFILE=~/.zsh_history
SAVEHIST=1000
HISTSIZE=1000

autoload -Uz compinit promptinit
compinit
promptinit

autoload -U colors && colors

export PROMPT="%{%B$fg[green]%}[%n@%m %c]$%{$reset_color%b%} "
export EDITOR=vim
export TERM=xterm-256color

bindkey -v
bindkey '^?' backward-delete-char
bindkey '^K' history-beginning-search-backward
bindkey '^J' history-beginning-search-forward

alias ls='ls --color=auto'
alias open='gvfs-open 2> /dev/null'
alias xclip='xclip -selection c'
alias b='popd'

function precmd() {
   print -Pn "\e]2;%m:%-3~ $a\a"
}

